/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        /* Brand Colors */
        burgundy: {
          50: 'rgb(var(--color-burgundy-50) / <alpha-value>)',
          100: 'rgb(var(--color-burgundy-100) / <alpha-value>)',
          200: 'rgb(var(--color-burgundy-200) / <alpha-value>)',
          300: 'rgb(var(--color-burgundy-300) / <alpha-value>)',
          400: 'rgb(var(--color-burgundy-400) / <alpha-value>)',
          500: 'rgb(var(--color-burgundy-500) / <alpha-value>)',
          600: 'rgb(var(--color-burgundy-600) / <alpha-value>)',
          700: 'rgb(var(--color-burgundy-700) / <alpha-value>)',
          800: 'rgb(var(--color-burgundy-800) / <alpha-value>)',
          900: 'rgb(var(--color-burgundy-900) / <alpha-value>)',
          950: 'rgb(var(--color-burgundy-950) / <alpha-value>)',
        },
        gold: {
          50: 'rgb(var(--color-gold-50) / <alpha-value>)',
          100: 'rgb(var(--color-gold-100) / <alpha-value>)',
          200: 'rgb(var(--color-gold-200) / <alpha-value>)',
          300: 'rgb(var(--color-gold-300) / <alpha-value>)',
          400: 'rgb(var(--color-gold-400) / <alpha-value>)',
          500: 'rgb(var(--color-gold-500) / <alpha-value>)',
          600: 'rgb(var(--color-gold-600) / <alpha-value>)',
          700: 'rgb(var(--color-gold-700) / <alpha-value>)',
          800: 'rgb(var(--color-gold-800) / <alpha-value>)',
          900: 'rgb(var(--color-gold-900) / <alpha-value>)',
          950: 'rgb(var(--color-gold-950) / <alpha-value>)',
        },
        emerald: {
          50: 'rgb(var(--color-emerald-50) / <alpha-value>)',
          100: 'rgb(var(--color-emerald-100) / <alpha-value>)',
          200: 'rgb(var(--color-emerald-200) / <alpha-value>)',
          300: 'rgb(var(--color-emerald-300) / <alpha-value>)',
          400: 'rgb(var(--color-emerald-400) / <alpha-value>)',
          500: 'rgb(var(--color-emerald-500) / <alpha-value>)',
          600: 'rgb(var(--color-emerald-600) / <alpha-value>)',
          700: 'rgb(var(--color-emerald-700) / <alpha-value>)',
          800: 'rgb(var(--color-emerald-800) / <alpha-value>)',
          900: 'rgb(var(--color-emerald-900) / <alpha-value>)',
          950: 'rgb(var(--color-emerald-950) / <alpha-value>)',
        },
        pink: {
          50: 'rgb(var(--color-pink-50) / <alpha-value>)',
          100: 'rgb(var(--color-pink-100) / <alpha-value>)',
          200: 'rgb(var(--color-pink-200) / <alpha-value>)',
          300: 'rgb(var(--color-pink-300) / <alpha-value>)',
          400: 'rgb(var(--color-pink-400) / <alpha-value>)',
          500: 'rgb(var(--color-pink-500) / <alpha-value>)',
          600: 'rgb(var(--color-pink-600) / <alpha-value>)',
          700: 'rgb(var(--color-pink-700) / <alpha-value>)',
          800: 'rgb(var(--color-pink-800) / <alpha-value>)',
          900: 'rgb(var(--color-pink-900) / <alpha-value>)',
          950: 'rgb(var(--color-pink-950) / <alpha-value>)',
        },
        red: {
          50: 'rgb(var(--color-red-50) / <alpha-value>)',
          100: 'rgb(var(--color-red-100) / <alpha-value>)',
          200: 'rgb(var(--color-red-200) / <alpha-value>)',
          300: 'rgb(var(--color-red-300) / <alpha-value>)',
          400: 'rgb(var(--color-red-400) / <alpha-value>)',
          500: 'rgb(var(--color-red-500) / <alpha-value>)',
          600: 'rgb(var(--color-red-600) / <alpha-value>)',
          700: 'rgb(var(--color-red-700) / <alpha-value>)',
          800: 'rgb(var(--color-red-800) / <alpha-value>)',
          900: 'rgb(var(--color-red-900) / <alpha-value>)',
          950: 'rgb(var(--color-red-950) / <alpha-value>)',
        },
        neutral: {
          50: 'rgb(var(--color-neutral-50) / <alpha-value>)',
          100: 'rgb(var(--color-neutral-100) / <alpha-value>)',
          200: 'rgb(var(--color-neutral-200) / <alpha-value>)',
          300: 'rgb(var(--color-neutral-300) / <alpha-value>)',
          400: 'rgb(var(--color-neutral-400) / <alpha-value>)',
          500: 'rgb(var(--color-neutral-500) / <alpha-value>)',
          600: 'rgb(var(--color-neutral-600) / <alpha-value>)',
          700: 'rgb(var(--color-neutral-700) / <alpha-value>)',
          800: 'rgb(var(--color-neutral-800) / <alpha-value>)',
          900: 'rgb(var(--color-neutral-900) / <alpha-value>)',
          950: 'rgb(var(--color-neutral-950) / <alpha-value>)',
        },
        /* Legacy aliases for backward compatibility */
        primary: {
          50: 'rgb(var(--color-burgundy-50) / <alpha-value>)',
          100: 'rgb(var(--color-burgundy-100) / <alpha-value>)',
          200: 'rgb(var(--color-burgundy-200) / <alpha-value>)',
          300: 'rgb(var(--color-burgundy-300) / <alpha-value>)',
          400: 'rgb(var(--color-burgundy-400) / <alpha-value>)',
          500: 'rgb(var(--color-burgundy-500) / <alpha-value>)',
          600: 'rgb(var(--color-burgundy-600) / <alpha-value>)',
          700: 'rgb(var(--color-burgundy-700) / <alpha-value>)',
          800: 'rgb(var(--color-burgundy-800) / <alpha-value>)',
          900: 'rgb(var(--color-burgundy-900) / <alpha-value>)',
          950: 'rgb(var(--color-burgundy-950) / <alpha-value>)',
        },
        secondary: {
          50: 'rgb(var(--color-neutral-50) / <alpha-value>)',
          100: 'rgb(var(--color-neutral-100) / <alpha-value>)',
          200: 'rgb(var(--color-neutral-200) / <alpha-value>)',
          300: 'rgb(var(--color-neutral-300) / <alpha-value>)',
          400: 'rgb(var(--color-neutral-400) / <alpha-value>)',
          500: 'rgb(var(--color-neutral-500) / <alpha-value>)',
          600: 'rgb(var(--color-neutral-600) / <alpha-value>)',
          700: 'rgb(var(--color-neutral-700) / <alpha-value>)',
          800: 'rgb(var(--color-neutral-800) / <alpha-value>)',
          900: 'rgb(var(--color-neutral-900) / <alpha-value>)',
          950: 'rgb(var(--color-neutral-950) / <alpha-value>)',
        },
        accent: {
          50: 'rgb(var(--color-gold-50) / <alpha-value>)',
          100: 'rgb(var(--color-gold-100) / <alpha-value>)',
          200: 'rgb(var(--color-gold-200) / <alpha-value>)',
          300: 'rgb(var(--color-gold-300) / <alpha-value>)',
          400: 'rgb(var(--color-gold-400) / <alpha-value>)',
          500: 'rgb(var(--color-gold-500) / <alpha-value>)',
          600: 'rgb(var(--color-gold-600) / <alpha-value>)',
          700: 'rgb(var(--color-gold-700) / <alpha-value>)',
          800: 'rgb(var(--color-gold-800) / <alpha-value>)',
          900: 'rgb(var(--color-gold-900) / <alpha-value>)',
          950: 'rgb(var(--color-gold-950) / <alpha-value>)',
        },
        success: {
          50: 'rgb(var(--color-emerald-50) / <alpha-value>)',
          100: 'rgb(var(--color-emerald-100) / <alpha-value>)',
          200: 'rgb(var(--color-emerald-200) / <alpha-value>)',
          300: 'rgb(var(--color-emerald-300) / <alpha-value>)',
          400: 'rgb(var(--color-emerald-400) / <alpha-value>)',
          500: 'rgb(var(--color-emerald-500) / <alpha-value>)',
          600: 'rgb(var(--color-emerald-600) / <alpha-value>)',
          700: 'rgb(var(--color-emerald-700) / <alpha-value>)',
          800: 'rgb(var(--color-emerald-800) / <alpha-value>)',
          900: 'rgb(var(--color-emerald-900) / <alpha-value>)',
          950: 'rgb(var(--color-emerald-950) / <alpha-value>)',
        },
        warning: {
          50: 'rgb(var(--color-gold-50) / <alpha-value>)',
          100: 'rgb(var(--color-gold-100) / <alpha-value>)',
          200: 'rgb(var(--color-gold-200) / <alpha-value>)',
          300: 'rgb(var(--color-gold-300) / <alpha-value>)',
          400: 'rgb(var(--color-gold-400) / <alpha-value>)',
          500: 'rgb(var(--color-gold-500) / <alpha-value>)',
          600: 'rgb(var(--color-gold-600) / <alpha-value>)',
          700: 'rgb(var(--color-gold-700) / <alpha-value>)',
          800: 'rgb(var(--color-gold-800) / <alpha-value>)',
          900: 'rgb(var(--color-gold-900) / <alpha-value>)',
          950: 'rgb(var(--color-gold-950) / <alpha-value>)',
        },
        error: {
          50: 'rgb(var(--color-red-50) / <alpha-value>)',
          100: 'rgb(var(--color-red-100) / <alpha-value>)',
          200: 'rgb(var(--color-red-200) / <alpha-value>)',
          300: 'rgb(var(--color-red-300) / <alpha-value>)',
          400: 'rgb(var(--color-red-400) / <alpha-value>)',
          500: 'rgb(var(--color-red-500) / <alpha-value>)',
          600: 'rgb(var(--color-red-600) / <alpha-value>)',
          700: 'rgb(var(--color-red-700) / <alpha-value>)',
          800: 'rgb(var(--color-red-800) / <alpha-value>)',
          900: 'rgb(var(--color-red-900) / <alpha-value>)',
          950: 'rgb(var(--color-red-950) / <alpha-value>)',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Playfair Display', 'serif'],
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-out',
        'slide-up': 'slideUp 0.5s ease-out',
        'slide-down': 'slideDown 0.3s ease-out',
        'scale-in': 'scaleIn 0.2s ease-out',
        'spin-slow': 'spin 3s linear infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideDown: {
          '0%': { opacity: '0', transform: 'translateY(-10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
      },
      boxShadow: {
        'soft': '0 8px 28px -12px rgba(36, 36, 36, 0.16)',
        'soft-lg': '0 18px 45px -18px rgba(36, 36, 36, 0.2)',
        'inner-soft': 'inset 0 1px 2px 0 rgba(36, 36, 36, 0.06)',
      },
    },
  },
  plugins: [],
}
